@url = https://orange-xylophone-w6w7jpww7gjh597w-8080.app.github.dev

GET {{url}}/filmes

###
GET {{url}}/filmes/3

###
POST {{url}}/filmes
Content-Type: application/json

{
    "titulo": "It - a Coisa",
    "idGenero": 4
}

###
PUT {{url}}/filmes/3
Content-Type: application/json

{
    "titulo": "It a Coisa",
    "idGenero": 2
}

###
DELETE {{url}}/filmes/3